### ISSUE TITLE
Vector display error when raster is turned on and off

### ISSUE THREAD

**Issue by Gyeongmin-Roh** [Geolicious/qgis2leaf#114]
I have a problem that vector layer are not missing when raster layer is turned on and off.
I seems that the raster layer goes on top of all existing layers.

1) Initial loading
![qgis2leaf_load](https://cloud.githubusercontent.com/assets/8922386/4431448/c28146d2-4667-11e4-999e-bdcb1e0720d3.jpg)

2) Raster is off
![qgis2leaf_raster_off](https://cloud.githubusercontent.com/assets/8922386/4431449/d964d22e-4667-11e4-9708-2c9e96167cbe.jpg)

3) Raster is on again
![qgis2leaf_raster_on](https://cloud.githubusercontent.com/assets/8922386/4431452/e79c114a-4667-11e4-87ea-6d72d258d94f.jpg)

Anyway, many thanks for this nice plugin.

**Comment by tomchadwin** [comment]
Here is some discussion of the issue in Leaflet. It looks as though it is to be addressed in Leaflet 0.8:

https://github.com/Leaflet/Leaflet/issues/2086
