### ISSUE TITLE
cluster not working in 2.6

### ISSUE THREAD

**Issue by LucaMoiana** [Geolicious/qgis2leaf#132]
Hi great plugin,

with 2.4 everything was fine, but, since I updated to 2.6, the make cluster option ain't working.

thanks again for this great plugin

**Comment by tomchadwin** [comment]
Has anyone looked at this since 2.8 was released? Is clustering still failing?

**Comment by LucaMoiana** [comment]
Looks to me that cluster is working on 2.8. 
L

**Comment by tomchadwin** [comment]
It's broken in master at the mo, but I think I have a fix.

**Comment by tomchadwin** [comment]
Fixed #246
