### ISSUE TITLE
No elements output if qgis have not some elements selected...

### ISSUE THREAD

**Issue by marcobra** [Geolicious/qgis2leaf#191]
using qgis2leaf at latest commit a3c9db0e11 (but also with previous commit, no issue with stable)
the exported layer have no data and not standard controls showed on it... 
all work if i select some elements in qgis and select option to export selected.

HTH

**Comment by tomchadwin** [comment]
Can you tell us more about this:

- what is the QGIS layer (SHP? WFS? etc)
- are you selecting "Encode to JSON" in the plugin dialog?
- any browser console error messages?

**Comment by riccardoklinger** [comment]
please, if possible share your data. ATM I have the issue when I do not select any layer and just selct a basemap the webmap fails to show me the basemap.

**Comment by tomchadwin** [comment]
Closing - no further details provided
