### ISSUE TITLE
"No basemap" function in 1.4.1?

### ISSUE THREAD

**Issue by jkwchui** [Geolicious/qgis2leaf#194]
Hello - first of all, thanks for the great plug-in.  I've been trying to show graphs using QGIS & Leaflet, so I was particularly interested in the option of not having a basemap / having custom basemaps added recently.
However, what I find is that by not selecting a base map, the vector layers are also not displayed; adding any base map restores the functionality in the export.  Is this a bug, or a misunderstanding of "no basemap" on my part?

**Comment by tomchadwin** [comment]
Definitely sounds like a bug to me. Let me try to reproduce.

**Comment by tomchadwin** [comment]
I can't immediately recreate that issue. You are clicking the Get Layers button before OK, are you?

**Comment by riccardoklinger** [comment]
ATM it is working for me as well (tested with 1.4.1 )

Strange!!!

_______________________________

Geolicious GbR
Agentur für Geo-Kommunikation

Riccardo Klinger
Geschäftsführer

mobil: 0176 63437298
e-mail: riccardo.klinger@geolicious.de
web: www.geolicious.de

Geolicious GbR
c/o Daniel Kerkow
Binzstraße 48
13189 Berlin

Gesellschafter:
Riccardo Klinger
Daniel Kerkow
Jakob Hafner

Sitz der Gesellschaft: Berlin
Ust-ID: DE289107523

**Comment by riccardoklinger** [comment]
check the video here: http://youtu.be/VuSc3gfwfUE

**Comment by jkwchui** [comment]
Hmm.  Let me check about the “Get Layers” option.

Jon

On 9 Jan, 2015, at 11:06 pm, Riccardo Klinger <notifications@github.com<mailto:notifications@github.com>> wrote:


check the video here: http://youtu.be/VuSc3gfwfUE

**Comment by tomchadwin** [comment]
Closing - cannot recreate, and no feedback from original reporter
