### ISSUE TITLE
How do I host this map on my local network?

### ISSUE THREAD

**Issue by ddd1600** [Geolicious/qgis2leaf#195]
This might not be the appropriate forum for this question, but how might I accomplish this. Currently I see its opening it directly from a file. I'm sure this is easy. Would appreciate a little hand holding though because I'm just a dumb rails developer :)

**Comment by riccardoklinger** [comment]
SOrry, I don't get it right. It's just a local file / set of files. Place them on your "home" server in a folder that's reachable in your network (/var/www/html on a ubuntu with apache). If this server is not connected with the world wide web you need to adjust the file exported. But this is another story. I need probvably more input from you @ddd1600

**Comment by mtravis** [comment]
Are you using Linux or Windows. If it's the later I would recommend
installing wamp: http://www.wampserver.com/en/
on your local server.

**Comment by ddd1600** [comment]
Yeah this was insanely easy. Just installed xampp and replaced the /htdocs directory's contents with the folder's contents.
