### ISSUE TITLE
AttributeError: 'QgsVectorLayer' object has no attribute 'editorWidgetV2'

### ISSUE THREAD

**Issue by permadhie** [Geolicious/qgis2leaf#197]
Hi,
I have tried to use this plugin, but it always return en error like below,

An error has occured while executing Python code:

Traceback (most recent call last):
  File "/Users/admin/.qgis2/python/plugins/qgis2leaf/qgis2leafdialog.py", line 297, in export2leaf
    qgis2leaf_exec(self.outFileName, self.basemapName, self.basemapMeta, self.basemapAddress, self.width, self.height, self.extent, self.full_screen, self.layer_list, self.visible, self.opacity, self.encode2JSON,self.createcluster, self.webpage_name, self.webmap_head,self.webmap_subhead, self.legend,self.locate,self.address, self.precision, self.labels, self.labelshover, self.matchCRS, self.selected)
  File "/Users/admin/.qgis2/python/plugins/qgis2leaf/qgis2leaf_exec.py", line 644, in qgis2leaf_exec
    if i.editorWidgetV2(fields.indexFromName(field)) != QgsVectorLayer.Hidden:
AttributeError: 'QgsVectorLayer' object has no attribute 'editorWidgetV2'

Is there any solution, so I can use this plugin normally?
Thanks,

**Comment by riccardoklinger** [comment]
@permadhie which QGIS version do you use? Which plugin version?

**Comment by permadhie** [comment]
below is the version of mine,
Python version:
2.6.1 (r261:67515, Jun 24 2010, 21:47:49) 
[GCC 4.2.1 (Apple Inc. build 5646)]

QGIS version:
2.0.1-Dufour Dufour, f738351

qgis2leaf plugin version:
1.4.1

Need your advice to make all of these thing work normally

Thanks,

**Comment by riccardoklinger** [comment]
Hi @permadhie ,

your QGIS version is outdated. Please upgrade to QGIS 2.6.1 or at least
QGIS 2.4 and report back

Best regards,

Riccardo

_______________________________

Geolicious GbR
Agentur für Geo-Kommunikation

Riccardo Klinger
Geschäftsführer

mobil: 0176 63437298
e-mail: riccardo.klinger@geolicious.de
web: www.geolicious.de

Geolicious GbR
c/o Daniel Kerkow
Binzstraße 48
13189 Berlin

Gesellschafter:
Riccardo Klinger
Daniel Kerkow
Jakob Hafner

Sitz der Gesellschaft: Berlin
Ust-ID: DE289107523

**Comment by permadhie** [comment]
I Installed those version cause my laptop still on Mac OSC 10.6.8 (Snow Leporad)
is there any way to make an upgrade QGIS's version without update my OSX?

**Comment by riccardoklinger** [comment]
dont know. check the page of kyng chaos.

_______________________________

Geolicious GbR
Agentur für Geo-Kommunikation

Riccardo Klinger
Geschäftsführer

mobil: 0176 63437298
e-mail: riccardo.klinger@geolicious.de
web: www.geolicious.de

Geolicious GbR
c/o Daniel Kerkow
Binzstraße 48
13189 Berlin

Gesellschafter:
Riccardo Klinger
Daniel Kerkow
Jakob Hafner

Sitz der Gesellschaft: Berlin
Ust-ID: DE289107523

**Comment by tomchadwin** [comment]
@riccardoklinger Probably worth checking what QGIS version compatibility we claim.

**Comment by riccardoklinger** [comment]
We started with claiming 2.2 and now we state 2.6 in the readme.md . We
don't say anything about downwards compability in the metadata.txt.

_______________________________

Geolicious GbR
Agentur für Geo-Kommunikation

Riccardo Klinger
Geschäftsführer

mobil: 0176 63437298
e-mail: riccardo.klinger@geolicious.de
web: www.geolicious.de

Geolicious GbR
c/o Daniel Kerkow
Binzstraße 48
13189 Berlin

Gesellschafter:
Riccardo Klinger
Daniel Kerkow
Jakob Hafner

Sitz der Gesellschaft: Berlin
Ust-ID: DE289107523

**Comment by tomchadwin** [comment]
Closing - incompatible QGIS version

**Comment by hercipri** [comment]
Traceback (most recent call last):
  File "C:/Users/Admin/.qgis2/python/plugins\qgis2leaf\qgis2leafdialog.py", line 297, in export2leaf
    qgis2leaf_exec(self.outFileName, self.basemapName, self.basemapMeta, self.basemapAddress, self.width, self.height, self.extent, self.full_screen, self.layer_list, self.visible, self.opacity, self.encode2JSON,self.createcluster, self.webpage_name, self.webmap_head,self.webmap_subhead, self.legend,self.locate,self.address, self.precision, self.labels, self.labelshover, self.matchCRS, self.selected)
  File "C:/Users/Admin/.qgis2/python/plugins\qgis2leaf\qgis2leaf_exec.py", line 468, in qgis2leaf_exec
    if symbol.symbolLayer(0).brushStyle() == 0:
AttributeError: 'QgsSimpleLineSymbolLayerV2' object has no attribute 'brushStyle'

Versiune Python:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

Versiune QGIS:
2.8.2-Wien Wien, 1b929ef

Cale Python: ['C:/Users/Admin/.qgis2/python/plugins\processing', 'C:\Users\Admin\.qgis2\python\plugins\navidata', 'C:\Users\Admin\.qgis2\python\plugins\GeoCoding\libs', 'C:/PROGRA~1/QGISWI~1/apps/qgis/./python', u'C:/Users/Admin/.qgis2/python', u'C:/Users/Admin/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis/./python/plugins', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg', 'C:\Program Files (x86)\ArcGIS\bin', 'C:\PROGRA~1\QGISWI~1\bin\python27.zip', 'C:\PROGRA~1\QGISWI~1\apps\Python27\DLLs', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\plat-win', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\lib-tk', 'C:\PROGRA~1\QGISWI~1\bin', 'C:\PROGRA~1\QGISWI~1\apps\Python27', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\PIL', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\win32', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\win32\lib', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\six-1.3.0-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg', 'C:\PROGRA~1\QGISWI~1\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg', u'C:/Users/Admin/.qgis2//python', 'C:\PROGRA~1\QGISWI~1\apps\qgis\python\plugins\fTools\tools', 'D:/+ONG/+proiect - Defl.Cris-Coridor/mat-promotionale/harta comuna']

**Comment by hercipri** [comment]
and I greet same error, help me pls

**Comment by riccardoklinger** [comment]
worked fine with qgis 2.8.2 and recent master. can you provide a screenshot
of current style settings of the layer?

---

Geolicious GbR
Agentur für Geo-Kommunikation

Riccardo Klinger
Geschäftsführer

mobil: 0176 63437298
e-mail: riccardo.klinger@geolicious.de
web: www.geolicious.de

Geolicious GbR
c/o Daniel Kerkow
Binzstraße 48
13189 Berlin

Gesellschafter:
Riccardo Klinger
Daniel Kerkow
Jakob Hafner

Sitz der Gesellschaft: Berlin
Ust-ID: DE289107523

**Comment by tomchadwin** [comment]
Current master does not have that code at line 468 of qgis2leaf_exec.py. As @riccardoklinger says, can you use current master and try again?

**Comment by hercipri** [comment]
![untitled-3](https://cloud.githubusercontent.com/assets/12398678/7571147/3e77c212-f81e-11e4-9959-7bf322515141.jpg)
![untitled-4](https://cloud.githubusercontent.com/assets/12398678/7571148/3e7b779a-f81e-11e4-8711-5e51dd0a93aa.jpg)

I attached two printscreen

some layers are displayed depending on the condition

**Comment by riccardoklinger** [comment]
I don't think we have included rule based rendering. please use rendering
by categories.

---

Geolicious GbR
Agentur für Geo-Kommunikation

Riccardo Klinger
Geschäftsführer

mobil: 0176 63437298
e-mail: riccardo.klinger@geolicious.de
web: www.geolicious.de

Geolicious GbR
c/o Daniel Kerkow
Binzstraße 48
13189 Berlin

Gesellschafter:
Riccardo Klinger
Daniel Kerkow
Jakob Hafner

Sitz der Gesellschaft: Berlin
Ust-ID: DE289107523

**Comment by tomchadwin** [comment]
Rule-based styles/rendering are not supported, I'm afraid, and it does not look likely that they will be soon.

**Comment by hercipri** [comment]
ok, thank you, too bad :(
I will change the attributes in db

**Comment by tomchadwin** [comment]
Or use something like the field calculator, so that you don't have to alter your underlying data.

**Comment by hercipri** [comment]
When the new  version will be available with the posibility of displaying layers  depending  on various conditions?

with pleasure

**Comment by tomchadwin** [comment]
@riccardoklinger I know I changed the code for simple, categorized and graduated to remove the styles from the JSON files. Do you think it would be worth reinstroducing that approach for rule-based? It means it would only work for JSON layers, not WFS (though WFS encoded to JSON would work, obviously). What do you think?

@NathanW2 said on qgis-dev that he might be able to do something to enable rule-based rendering for us, but I've not heard back: http://osgeo-org.1560.x6.nabble.com/Python-granular-access-to-rules-in-rule-based-renderer-td5201632.html

**Comment by tomchadwin** [comment]
By the way, rule based was already requested in #110
