### ISSUE TITLE
Visible layers not working correctly

### ISSUE THREAD

**Issue by edspeth** [Geolicious/qgis2leaf#198]
The "Visible layers - show none" option isn't working for polygon layers, it displays the layers no matter what. (The layer is commented out correctly in index.html but the layer still displays on the map).

The same layers converted to lines work fine.

When you have a mix of line and polygon layers - if the line layers are on top of the polygon layers in QGIS then the line layers display will be correct (polygons still always displayed). If the polygon layers are on top then even the line layers below display when they shouldn't.

**Comment by tomchadwin** [comment]
Looking at the code, the "Visible layers" drop-down option might only apply to layers encoded to JSON. Are the bugs you see with layers encoded to JSON, or with WFS?

**Comment by edspeth** [comment]
Yes the layers are encoded to JSON. The HTML looks correct in all circumstances in that the layers get commented out correctly, but in the case of the errors listed above, they layers still appear when commented out.

**Comment by tomchadwin** [comment]
This error seems to stem from my code to ensure layer order is preserved. In working layers (simple point and line), the sorting code is:

```javascript
for (index = 0; index < layerOrder.length; index++) {
	feature_group.removeLayer(layerOrder[index]);feature_group.addLayer(layerOrder[index]);
}
```
In non-working layers (simple poly), it is this:

```javascript
for (index = 0; index < layerOrder.length; index++) {
	map.removeLayer(layerOrder[index]);map.addLayer(layerOrder[index]);
}
```
Changing `map` to `feature_group` seems to fix things. @edspeth is looking to see which categorized/graduated styles are also affected.

**Comment by edspeth** [comment]
It's working fine with this amendment.

**Comment by tomchadwin** [comment]
Fixed #203

**Comment by edspeth** [comment]
JSON layers working fine.

Now having the problem with a WFS polygon layer. The layer is always displayed on initial view of the map irrespective of whether it's commented out in index.html.

**Comment by tomchadwin** [comment]
Confirmed.

**Comment by tomchadwin** [comment]
Please test PR #207 against this issue.

**Comment by tomchadwin** [comment]
I think this fix has caused a regression in WFS layer stacking order. I think that changing map to feature_group in the restacking code (as above) should only be done in the case of clustered layers, or something like that. I don't yet fully understand it, but believe this could be the root of the layer stacking issue.

**Comment by tomchadwin** [comment]
Hopefully #255 has now fixed this
