### ISSUE TITLE
Set correct document mode for IE

### ISSUE THREAD

**Issue by magerlin** [Geolicious/qgis2leaf#204]
To make Internet Explorer 10 open the map from a web server I had to add this in the index.html file.

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

Otherwise IE opens the map in document mode 7 which is not working.

**Comment by tomchadwin** [comment]
I think that's treating the symptom, not the cause. Can you double-check that, without your extra <meta> tag, IE10 assigns the map page to its "Intranet zone"?

**Comment by magerlin** [comment]
Hi Tom

I am not quite sure how to check that.

I am on a company PC and as far as I can see then the definition of Local intranet is locked by a company policy. I cannot myself add any sites.

But strangely enough I just made a quick map showing an OSM street network and I can open it without any problem in IE10???


Yours sincerely
Morten
