### ISSUE TITLE
Unexpected layers shown

### ISSUE THREAD

**Issue by chrishamby** [Geolicious/qgis2leaf#206]
I'm exporting a project with 14 layers - users will only use one or two at a time so I set Visible Layers to Shown None. I notice that certain layers end up loading in the new map anyway. 

I'm not completely sure why certain layers are visible and certain ones are not, but my guess is that is has something to do with the geometry type. The simple polygon layers are visible when the map is loaded, but the multiline, point, and multipolygon layers are not. 

![image](https://cloud.githubusercontent.com/assets/1383739/6485872/ddcd41de-c254-11e4-8f6b-ce6572a91632.png)

**Comment by chrishamby** [comment]
I apologize for being vague, as my knowledge of programming languages is very limited. I found the snippet of code that seemed to be the culprit - commenting it out appeared to fix it.
```
var exp_AssemblyJSON = new L.geoJson(exp_Assembly,{
					onEachFeature: pop_Assembly,
					style: function (feature) {
						return {color: feature.properties.border_color_qgis2leaf,
								fillColor: feature.properties.color_qgis2leaf,
								weight: feature.properties.radius_qgis2leaf,
								opacity: feature.properties.transp_qgis2leaf,
								fillOpacity: feature.properties.transp_qgis2leaf};
						}
					});
				feature_group.addLayer(exp_AssemblyJSON);
				//layerOrder[layerOrder.length] = exp_AssemblyJSON;
				for (index = 0; index < layerOrder.length; index++) {
					map.removeLayer(layerOrder[index]);map.addLayer(layerOrder[index]);
				}
				
						//delete comment sign to show this layer on the map in the initial view.
						//exp_AssemblyJSON.addTo(map);
```

**Comment by tomchadwin** [comment]
While I'm sure you are using the latest version of the plug-in according to the QGIS plug-in manager, I think some recent patches here on Github could sorry the problem. 

Specifically,  uncomment what you commented out, and two lines later, change both occurrences of map to feature_group:

feature_group.removeLayer(layerOrder[index]); feature_group.addLayer(layerOrder[index]);

**Comment by chrishamby** [comment]
Thank you. I did that and things appear to be working fine. Forgive my ignorance of javascript, but will my map work without major issues with the hack I implemented above? I currently have a map in production with it that I'd rather not update just yet if I don't need to.

**Comment by tomchadwin** [comment]
The line you commented out is what makes sure that the stacking order of your layers in QGIS is reproduced in your Leaflet map. If that order is not critical to you, then you can safely leave that line out.
