### ISSUE TITLE
Remove style from JSON files

### ISSUE THREAD

**Issue by tomchadwin** [Geolicious/qgis2leaf#212]
At the moment, GeoJSON-encoded layers have style information embedded into them. I don't think there is any need to do this. If we duplicate the method of symbolizing from the WFS code, it negates the need to do this. The result:

- plugin runs faster, as JSON files don't have to be reopened and amended
- GeoJSON files contain only data from QGIS, not extra symbology info, so are more meaningful data, and load quicker
- perhaps this could push toward removing one of the two big loops in qgis2leaf_exec

I hope to look at this over the next few weeks.

**Comment by riccardoklinger** [comment]
this would be a great feature. I've included it in the tab as it is possible to have an unknown number of classes which would result in a hard and long list of if-else statements in the style definition. so I decided to put it directly into the json.

**Comment by tomchadwin** [comment]
Fixed: #215, #221, #224, #225
