### ISSUE TITLE
disable save as geojson option

### ISSUE THREAD

**Issue by riccardoklinger** [Geolicious/qgis2leaf#218]
many different WFS servers have restrictions on using/downloading/sharing their data. To keep it simple we should not offer to donwload the wfs as geojson.
Otherwise I will need some legal support/Q&A on this issue...

**Comment by tomchadwin** [comment]
I'm not sure I agree. Isn't that the responsibility of the user, not the plug-in? We manage WFSes from which we are happy to allow people to download JSON.

**Comment by riccardoklinger** [comment]
Then we should get somehow a really good statement as popup so the user
definitely understand that he is responsible for respecting the license of
the WFS owner! None of us would like to be responsible for a "Geo-Napster"
of the future.

_______________________________

Geolicious GbR
Agentur für Geo-Kommunikation

Riccardo Klinger
Geschäftsführer

mobil: 0176 63437298
e-mail: riccardo.klinger@geolicious.de
web: www.geolicious.de

Geolicious GbR
c/o Daniel Kerkow
Binzstraße 48
13189 Berlin

Gesellschafter:
Riccardo Klinger
Daniel Kerkow
Jakob Hafner

Sitz der Gesellschaft: Berlin
Ust-ID: DE289107523

**Comment by tomchadwin** [comment]
I still disagree. If the owner of the data on a WFS wants to limit how that data is used, they should reconsider using WFS. To put it another way, does QGIS give such a warning? Do any other WFS clients?

**Comment by mtravis** [comment]
I'm inclined to agree with @tomchadwin. Emphasis should be on plugin user
and the owner of the WFS server to make it secure.

**Comment by riccardoklinger** [comment]
QGIS doesn't warn you on downloading. So we won't do it either... I'll close this!
