### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by tomchadwin** [Geolicious/qgis2leaf#222]
I introduced jQuery back around 0.7. I think it is only used to load WFS via AJAX, which is overkill. We should replace this with:

https://github.com/calvinmetcalf/leaflet-ajax/

I did try this before, and could not get it to work. Can someone else crack it?

**Comment by mtravis** [comment]
@tomchadwin

Are you not just using a CDN for jquery - is that problematic.

Are you proposing a local download of the ajax plugin instead then.

Cheers

Matt

**Comment by tomchadwin** [comment]
@mtravis My issue is not about whether js files are local or CDN. My issue is that I don't think we need to use jQuery at all in the plug-in now - that it is unnecessary, since @calvinmetcalf's Leaflet ajax plug-in will do only what we need, rather than loads more that we don't.

**Comment by mtravis** [comment]
@tomchadwin Fair enough.

So when you call a cdn does it get everything in the library or does the
browser just call a particular function from that library when asked upon?

**Comment by tomchadwin** [comment]
The latter - a CDN is just a distributed remote storage location, so the whole of jQuery gets downloaded. Leaflet-ajax is one tenth the size of jQuery (minfied versions of both compared).

**Comment by mtravis** [comment]
I see. I can take a look at using the AJAX plugin next week if you can
wait.

**Comment by tomchadwin** [comment]
Of course - not urgent at all. And thanks.

**Comment by riccardoklinger** [comment]
i agree with @tomchadwin : I think we dont need the jquery call. will test it.

**Comment by tomchadwin** [comment]
I've had some success with this, and without even using the AJAX plugin. It once again makes layer stacking order problematic, but if I can crack that, we might be able to implement this. I've only got it working in the output file, though, so I have to implement it in the plugin itself, as well.

**Comment by tomchadwin** [comment]
Layer order possibly sorted, so I might have a solution for this. It has the significant side benefit of simplifying the output code even further. Trying to build the new output code into the plugin now. Will commit when I can.

**Comment by tomchadwin** [comment]
Done #259 - please test.
