### ISSUE TITLE
Opacity characteristics for polygons are not working

### ISSUE THREAD

**Issue by samelepetit** [Geolicious/qgis2leaf#258]
When exporting my layers, the opacity characteristics of the polygons are not exported, so they apear as solid, so the basemap beneath the polygons is hidden.

**Comment by riccardoklinger** [comment]
Please paste a screenshot of your current Layer settings in style

**Comment by samelepetit** [comment]
![layer_style](https://cloud.githubusercontent.com/assets/11983053/7188679/d18d5c16-e436-11e4-9d47-a1d7f8cc70de.png)

**Comment by tomchadwin** [comment]
Which versions of QGIS and qgis2leaf are you using? Transparency support was improved recently.



On 16 Apr 2015, at 19:48, samelepetit <notifications@github.com<mailto:notifications@github.com>> wrote:


[layer_style]<https://cloud.githubusercontent.com/assets/11983053/7188679/d18d5c16-e436-11e4-9d47-a1d7f8cc70de.png>

—
Reply to this email directly or view it on GitHub<https://github.com/Geolicious/qgis2leaf/issues/258#issuecomment-93812614>.



Tom Chadwin, ICT Manager
Telephone: 01434 611530 Mob:
Web: www.northumberlandnationalpark.org.uk<http://www.northumberlandnationalpark.org.uk/>

IMPORTANT NOTICE - Disclaimer - This communication is from Northumberland National Park Authority (NNPA).The Authority’s head office and principal place of business is Eastburn, South Park, Hexham, Northumberland, NE46 1BS, United Kingdom. If you are not the intended recipient(s) please note that any form of disclosure, distribution, copying or use of this communication or the information in it or in any attachments is strictly prohibited and may be unlawful. If you have received this communication in error, please delete the email and destroy any copies of it. Any views or opinions presented are solely those of the author and do not necessarily represent those of NNPA.Contractors or potential contractors are reminded that a formal Order or Contract is needed for NNPA to be bound by any offer or acceptance of terms for the supply of goods or services Although this email and any attachments are believed to be free of any virus or other defects which might affect any computer or IT system into which they are received, no responsibility is accepted by the NNPA for any loss or damage arising in any way from the receipt or use thereof. Computer systems of this Authority may be monitored and communications carried out on them recorded, to secure the effective operation of the system and for other lawful purpose.

**Comment by samelepetit** [comment]
I'm using QGIS 2.8.1 Wein and qgis2leaf 1.5.2.
The last version of qgis2leaf was working correctly on transparency.

![img1](https://cloud.githubusercontent.com/assets/11983053/7190411/5708d5e4-e443-11e4-8277-b9f00cf19576.png)
![img2](https://cloud.githubusercontent.com/assets/11983053/7190415/5df51c3c-e443-11e4-8bc4-5832211126c8.png)

**Comment by tomchadwin** [comment]
You're right. For categorized polygons, only symbol transparency is imported, not layer transparency. I'll patch as soon as I can.



On 16 Apr 2015, at 21:21, Samuel Valiente <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm using QGIS 2.8.1 Wein and qgis2leaf 1.5.2.
The last version of qgis2leaf was working correctly on transparency.

[img1]<https://cloud.githubusercontent.com/assets/11983053/7190411/5708d5e4-e443-11e4-8277-b9f00cf19576.png>
[img2]<https://cloud.githubusercontent.com/assets/11983053/7190415/5df51c3c-e443-11e4-8bc4-5832211126c8.png>

—
Reply to this email directly or view it on GitHub<https://github.com/Geolicious/qgis2leaf/issues/258#issuecomment-93830881>.



Tom Chadwin, ICT Manager
Telephone: 01434 611530 Mob:
Web: www.northumberlandnationalpark.org.uk<http://www.northumberlandnationalpark.org.uk/>

IMPORTANT NOTICE - Disclaimer - This communication is from Northumberland National Park Authority (NNPA).The Authority’s head office and principal place of business is Eastburn, South Park, Hexham, Northumberland, NE46 1BS, United Kingdom. If you are not the intended recipient(s) please note that any form of disclosure, distribution, copying or use of this communication or the information in it or in any attachments is strictly prohibited and may be unlawful. If you have received this communication in error, please delete the email and destroy any copies of it. Any views or opinions presented are solely those of the author and do not necessarily represent those of NNPA.Contractors or potential contractors are reminded that a formal Order or Contract is needed for NNPA to be bound by any offer or acceptance of terms for the supply of goods or services Although this email and any attachments are believed to be free of any virus or other defects which might affect any computer or IT system into which they are received, no responsibility is accepted by the NNPA for any loss or damage arising in any way from the receipt or use thereof. Computer systems of this Authority may be monitored and communications carried out on them recorded, to secure the effective operation of the system and for other lawful purpose.

**Comment by samelepetit** [comment]
Thank you very much for your support.

**Comment by tomchadwin** [comment]
Fixed #259. Can you try current master and let me know if that is now fixed?

**Comment by samelepetit** [comment]
It is fixed, thanks again.

**Comment by tomchadwin** [comment]
Splendid. Glad it's working
