### ISSUE TITLE
Put aside style

### ISSUE THREAD

**Issue by cbertelli** [Geolicious/qgis2leaf#268]
This is a possible enhancement.
Qgis2leaf put style in every record. This increases the size of the json file and makes adjusting style very difficult afterwards.
Could you put the styles elsewhere, say in a specific file, in the body of the page (under a conditional structure to handle the cases)?

**Comment by tomchadwin** [comment]
Are you running the most recent version of qgis2leaf? The styles are no longer embedded into the JSON layer files. See #212.
